### PR TITLE
feat(extras): Add an S3 Multipart Upload helper

### LINKED ISSUE #30: S3: Offer a ManagedUpload (multipart upload) implementation
Looking at [`s3.upload()`](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L1275-L1287), that specific function is implemented by the [`AWS.S3.ManagedUpload`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html) class. It appears to chop your stream into individual 5MB segments and upload them with a [Multipart Upload](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) strategy. This is actually separate from streaming request bodies because each 'part' is buffered. So I will track managed/multipart uploads in a separate issue 😅 

_Originally posted by @danopia in https://github.com/cloudydeno/deno-aws_api/issues/24#issuecomment-1084962149_

### PR DESCRIPTION
**Pull request by danopia**
Comparable in outcome to the SDK's AWS.S3.ManagedUpload class.

Fixes #30 

## Example

```ts
import { ApiFactory } from 'https://deno.land/x/aws_api/client/mod.ts';
import { S3 } from 'https://deno.land/x/aws_api/services/s3/mod.ts';
// The new module:
import { managedUpload } from 'https://deno.land/x/aws_api/extras/s3-upload.ts';

const s3 = new ApiFactory().makeNew(S3);

const {VersionId} = await managedUpload(s3, {
    Bucket: 'my-bucket',
    Key: 'my-key',
    Body: await Deno.open('data.bin').then(x => x.readable),
});
```

## Remaining work

* [ ] Unit tests
* [ ] Report progress? Number of parts uploaded so far?
* [x] Parallelization of part upload (default 4)
* [x] Maybe refactor to use streams better?

### CODE REVIEW

**Comment by TillaTheHun0** [comment]
@danopia I was able to pull that helper in and it works, nicely done! I am going to run it through some load to see if there are any noticeable performance improvements.

**Comment by danopia** [comment]
Excellent, thanks for the validation effort ❤️

In my quick tests I noticed that memory usage isn't excellent. It seems that aws-api makes a copy or two of each request payload, so the default 20mb buffer (5mb*4) can actually become 60mb or so. That's not related to this helper, so I'll probably look at optimizing memory in a different PR.

**Comment by TillaTheHun0** [comment]
@danopia performance did seem to improve, in particular for larger files approaching the 1-2 MB size. Though that would make sense. Pretty sweet!

Memory usage did seem to increase, but CPU increased more in the tests that I ran.

This was running on a container on Fargate with 1 vCPU and 2048 GB of memory, fwiw.

**Comment by danopia** [comment]
I'll merge this in the coming days (just a couple more unit tests) and then also verify with some of the other S3 providers before tagging a release.

Note that the function is now named `managedUpload` to match AWS SDK, because it only multi-parts on files larger than 5MB so the name was misleading in the end.

**Pull request merged**
