### PR TITLE
WIP: Streaming request bodies (for S3)

### PR DESCRIPTION
**Pull request by danopia**
Turns out this is pretty tough API-wise because S3 uploads must have a `content-length` header, so the only way to 'stream' an upload of truely unknown length is to initiate a multi-part upload.

### CODE REVIEW

**Comment by TillaTheHun0** [comment]
+1 for this api. Right now, I am using `putObject` which accepts a `Buffer` or more broadly speaking, a `Uint8Array`, but I have to read the whole file into the buffer and send it.

With a streaming api, similar to AWS SDK's `upload`, I could pipe a request body directly to s3, which would greatly increase performance.

**Comment by danopia** [comment]
> With a streaming api, similar to AWS SDK's `upload`, I could pipe a request body directly to s3, which would greatly increase performance.

Thank you for reporting your use-case!

So looking at [`upload()`](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L1275-L1287), that specific function is implemented by the [`AWS.S3.ManagedUpload`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html) class. It appears to chop your stream into individual segments and upload them with a [Multipart Upload](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html) strategy. This is actually separate from streaming request bodies because each 'part' is buffered. So I will track managed/multipart uploads in a separate issue 😅 

S3 only supports true streaming uploads if you will know the length of the body upfront. That's what this PR ⬆️ implements. Maybe you know your object size ahead of time, in which case you don't actually need the multipart `upload()` (but the parallelization probably still helps speeds with huge objects)

**Comment by danopia** [comment]
@TillaTheHun0 I have a working pass on chunked/parallelized S3 uploading in #31, please feel free to vet the behavior in your own stuff before I get it clean enough to merge. You can `import { multiPartUpload } from "https://raw.githubusercontent.com/cloudydeno/deno-aws_api/89703336482f008f3f6ebd9f759370fd393ba362/lib/helpers/s3-upload.ts"` and then call it with an S3 client as shown in #31's text. If you have any feedback please comment on that PR. Thanks again!

**Comment by TillaTheHun0** [comment]
@danopia oh sweet, I will check it out! 👍

**Comment by yogesnsamy** [comment]
> +1 for this api. Right now, I am using `putObject` which accepts a `Buffer` or more broadly speaking, a `Uint8Array`, but I have to read the whole file into the buffer and send it.
> 
> With a streaming api, similar to AWS SDK's `upload`, I could pipe a request body directly to s3, which would greatly increase performance.

@TillaTheHun0 May I know how to supply a `Buffer` to `putObject`? Looking at the `s3.file`, I could only supply either one of the following values:
- Uint8Array
- string

image

**Comment by TillaTheHun0** [comment]
@yogesnsamy the code is [here](https://github.com/hyper63/hyper-adapter-namespaced-s3/blob/5d1703e64486d503ab2317272f6c23062fcc416d/adapter.js#L235)

Basically we're using [`readAll`](https://deno.land/std@0.159.0/streams/conversion.ts?s=readAll)which accepts a `Deno.Reader` and reads the contents into a `Uint8Array` that we pass to `putObject`

**Comment by yogesnsamy** [comment]
> @yogesnsamy the code is [here](https://github.com/hyper63/hyper-adapter-namespaced-s3/blob/5d1703e64486d503ab2317272f6c23062fcc416d/adapter.js#L235)
> 
> Basically we're using [`readAll`](https://deno.land/std@0.159.0/streams/conversion.ts?s=readAll)which accepts a `Deno.Reader` and reads the contents into a `Uint8Array` that we pass to `putObject`

Many thanks @TillaTheHun0. It works.

**Comment by danopia** [comment]
Question for y'all, when calling PutObject, do you know the size of your Reader upfront? That would make streaming easier to implement

**Comment by danopia** [comment]
🚀 [A managed-upload module](https://deno.land/x/aws_api@v0.8.0/extras/s3-upload.ts?s=managedUpload) (using S3 multipart) just shipped in `v0.8.0`. This is most useful for uploading large files (50MB and up) as it will break up your `ReadableStream<Uint8Array>` into multiple S3 requests.

🗒️ Also, hot tip: in cases where you aren't worried about the file fitting into memory, you can use a `Response` to easily buffer a `ReadableStream<Uint8Array>`:

```ts
const bodyBuffer = new Uint8Array(await new Response(bodyStream).arrayBuffer());
```

🗑️ This pull request is still in draft and I don't think it's going to land this time because it's not very useful. True request streaming is only possible to S3 _if the body's length is known upfront_. That limitation means that this library cannot just accept a `ReadableStream<Uint8Array>` on its own. The library could buffer the stream up for you, but this would really be a lie, so I'm not immediately in favor of it 🤔

**Pull request closed without merging**
